# Generated by Django 4.2.16 on 2025-10-28 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nipon_cars.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nipon_cars', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/', validators=[nipon_cars.models.validate_image]),
        ),
    ]
